# Configuración de puerto y nombre de aplicación
server.port=8080
spring.application.name=Boletera

# Importa la configuración local con credenciales reales.
spring.config.import=optional:classpath:application-local.properties

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/boleteradb?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cloudinary
cloudinary.cloud_name=dnf8jpcu1
cloudinary.api_key=471766721845585
cloudinary.api_secret=1ufu9-syFOQPO5kEXZuBbH2eqe0

# Seguridad
# Secreto para firmar los JWT
app.jwt.secret=jLCyF1BYw9Um738XMcsPlpJQoKfavTg52db6iHhxVkOR4tZIGWuzArnS0qeNED
# Credenciales del administrador inicial
app.admin.email=admin@ticketplace.com
app.admin.password=Admin123!
