# Configuración de puerto y nombre de aplicación
server.port=8080
spring.application.name=Boletera

# (Opcional) Usamos H2 en memoria para que Spring Data JPA pueda arrancar feliz
# sin necesidad de tener un servidor MySQL encendido.
spring.datasource.url=jdbc:mysql://localhost:3306/gamevaultdb?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true